# Generated by Django 4.2.30 on 2026-08-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=39.0, max_digits=10, null=True),
        ),
    ]
