# Generated by Django 4.2.30 on 2026-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(help_text='Author, Director, or Artist name', max_length=200)),
                ('category', models.CharField(choices=[('books', 'Book'), ('documentary', 'Documentary'), ('arts', 'Art Section')], default='books', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=39.0, max_digits=10)),
                ('file', models.FileField(upload_to='media_files/')),
            ],
        ),
    ]
