# Generated by Django 4.2.30 on 2026-08-10 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_purchasedbook_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedDocumentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('documentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.documentary')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_documentaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'documentary')},
            },
        ),
        migrations.CreateModel(
            name='PurchasedArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.art')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_arts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'art')},
            },
        ),
    ]
