# Generated by Django 4.2.30 on 2026-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_purchaseddocumentary_purchasedart'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
